### ISSUE TITLE
Single photo icon appearing when app is launched

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#18]
Know this may be fixed anyway as UI changes are made but on the basis that feedback is good just noticed that a single photo appears when I launch the website, despite me trying different browsers and in private tabs to stop cached data being used - I see this on going to actdev.cyipt.bike: 

![image](https://user-images.githubusercontent.com/1825120/108707295-b3669f00-7507-11eb-8f88-c8a67c61f313.png)

Intended behaviour? Guess not, low priority but seemed worth reporting, linked to the question of which layers are 'on' by default which in turn is linked to #13.

**Comment by Siequnu** [comment]
That's because the photo layer is turned on. Only the Great Kneighton site has content, hence the only pins appear there.

**Comment by Robinlovelace** [comment]
> Could you confirm that the layer is on?

It is. Not sure it should be by default.

**Comment by Siequnu** [comment]
In the final UI we will be changing the concept of map controls as per the concept, with the photos appearing as a carousel in the infographic rather than icons on the map. They won't be a default layer with pins, like the above screenshot.

I'll close this issue for now, as both the national- and site-level zooms will be overhauled in the coming weeks.

**Comment by mvl22** [comment]
I did switch it on by default. I'll disable it as yes it doesn't actually work well in the alpha map context - was just to get the photo selection data starting to be generated.

**Comment by Robinlovelace** [comment]
So this issue probably should have been closed when that commit went in. Good to have it switch on by default when testing, makes sense :+1:
