### ISSUE TITLE
Walking routes not weighted by level of use

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#20]
![image](https://user-images.githubusercontent.com/1825120/108728539-9b9c1480-7521-11eb-9925-a4e8fd5ae656.png)

Another one that will probably come good after #13.

**Comment by Siequnu** [comment]
Good catch, I'll take action on this and implement this in the layer definition.

**Comment by mvl22** [comment]
Quick update: I've been scoping out the changes need to implement this and have identified what changes I think are needed.

This is not a simple addition of a list of missing widths. The reason this doesn't work is because within the layer (routes) there is a width stops definition, but there are actually four separate sub-layers, all of which use that single set of width stops. The fix is to add support for defining a set of width stops per sub-layer, so that each sub-layer can have its own set of width stops based on a different property being read in each sub-layer.

So where we currently have the following (note `{%type}` in the file path):

```
            apiCall: 'https://raw.githubusercontent.com/cyipt/actdev/main/data-small/{site_name}/routes-{%type}.geojson',
            lineWidthField: 'cycle_base',
            lineWidthStops: [
                [999999, 9],
                [500, 8],
                [200, 7],
                [100, 6],
                [50, 5],
                [10, 4],
                [5, 3],
                [3, 2],
                [0, 1]
            ],
```

this will become something like this, where a new 'lineWidthStopsSublayerField' option specifies which drop-down value to switch on, and then that is used to disambiguate the other options.

```
            apiCall: 'https://raw.githubusercontent.com/cyipt/actdev/main/data-small/{site_name}/routes-{%type}.geojson',
            lineWidthStopsSublayerField: 'type',
            lineWidthField: {
                 'walk': 'walk_base',
                 'quiet,balanced,fast': 'cycle_base'
            },
            lineWidthStops: {
                 'walk': [
                    // other new stops here
                ]
                 'quiet,balanced,fast': [
                    [999999, 9],
                    [500, 8],
                    [200, 7],
                    [100, 6],
                    [50, 5],
                    [10, 4],
                    [5, 3],
                    [3, 2],
                    [0, 1]
                ]
            },
```

**Comment by Robinlovelace** [comment]
Thanks for the clear status update and suggested next steps. If there's anything we can do on the data side to help with this let me know although I want to minimise data changes over the next few days.

**Comment by mvl22** [comment]
I did think about whether the two distinct data fields could have a new one created, representing a common denominator, but I rapidly came to the conclusion this wouldn't work - there will still be different scales, etc. The above amended layer definition structure is the correct architectural approach.

**Comment by Siequnu** [comment]
These are now styled.

**Comment by mvl22** [comment]
Weighting by thickness now in place.

Colouring disabled, to avoid any inconsistency-related confusion with colouring for busyness on the other route types.

![Screenshot 2021-03-10 at 13 40 10](https://user-images.githubusercontent.com/361423/110638235-32b1cf00-81a6-11eb-80c5-651f42147668.png)
