### ISSUE TITLE
Unexpected variation of width

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#5]
Looks weird, should size be relative to cycling/walking/all trips? I think so.

https://actdev.cyipt.bike/sites,routes,accessibility/#11.31/53.7397/-1.4075

Screenshot below.

![image](https://user-images.githubusercontent.com/1825120/107347606-e5b2de00-6abd-11eb-815a-c143e452b61d.png)

**Comment by Siequnu** [comment]
Width and colour are both on the same gradient (data source) right now. 

I’ll change it to your first suggestion.

**Comment by mvl22** [comment]
Fixing this properly is essentially blocked on

https://github.com/cyipt/actdev/issues/54#issuecomment-775834372

**Comment by mvl22** [comment]
Now fixed, and I've tuned the thicknesses to try to ensure they work both (a) in absolute terms with the area of each site as well as (b) in relative terms between each site (e.g. Cambridge lines should be thicker than other areas of the country because more people are cycling).

Branching off of cyclists does now appear quite nicely I think, backing the data work.

![Screenshot 2021-02-09 at 19 32 41](https://user-images.githubusercontent.com/361423/107417557-a6ac7900-6b0d-11eb-9b9b-a019c2c62b11.png)

![Screenshot 2021-02-09 at 19 32 55](https://user-images.githubusercontent.com/361423/107417578-ac09c380-6b0d-11eb-90ae-7a9ed44e3d80.png)
