### ISSUE TITLE
Landing page does not always take you to the site you click on

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#53]
Example shown for Micklefield that I was wanting to check in response to a question from Dustin.

![Peek 2021-03-08 17-05](https://user-images.githubusercontent.com/1825120/110355082-c19cdb00-8030-11eb-875a-9acccb583745.gif)

Can anyone else reproduce this on Firefox?

Worth fixing if not prohibitively time-consuming if so.

**Comment by dabreegster** [comment]
In Firefox 86.0, private tab:
![screencast](https://user-images.githubusercontent.com/1664407/110378014-f0538b00-8009-11eb-90c6-2e050050ebf3.gif)
Part of the problem seems to be the whitespace oddness:
![Screenshot from 2021-03-08 12-29-46](https://user-images.githubusercontent.com/1664407/110378073-03fef180-800a-11eb-9fd9-763d14c26ff0.png)

**Comment by Robinlovelace** [comment]
Confirmed. It took me straight there showing what a car dependent location it is.

![image](https://user-images.githubusercontent.com/1825120/110448429-1be17e80-80b9-11eb-83e3-1da4bea911f5.png)
