### ISSUE TITLE
ClockBoard colourscheme

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/actdev-ui#63]
Currently it shows green for segments that seem quite busy:

![image](https://user-images.githubusercontent.com/1825120/110689167-4aa34600-81da-11eb-923a-75ddfb9e89c3.png)

For Handforth:

![image](https://user-images.githubusercontent.com/1825120/110689267-67d81480-81da-11eb-9d29-3886c3b92798.png)

Related: I suggest we go with this colourscheme for busyness for consistency and change the legend title accordingly - more important than the circuity ratings.

![image](https://user-images.githubusercontent.com/1825120/110689450-98b84980-81da-11eb-8f0f-b5b5a3ffed82.png)

**Comment by mvl22** [comment]
Hmm, looks like the colours were the wrong way round; amazed that no-one spotted this till now!

![Screenshot 2021-03-10 at 20 09 26](https://user-images.githubusercontent.com/361423/110691113-a1aa1a80-81dc-11eb-88ae-8955d0c5f685.png)

**Comment by mvl22** [comment]
I think the accessibility layer colour scheme has to be different to the lines layer otherwise the lines will be invisible as they'll be the same colour much of the time.

**Comment by Robinlovelace** [comment]
> Hmm, looks like the colours were the wrong way round; amazed that no-one spotted this till now!

Me too!

**Comment by mvl22** [comment]
Actually, it turned out that, the colours were still not always right, even though they were at least the right way round.

We were using interpolation, which it turns out in Mapbox GL language doesn't mean what I commonly understand as interpolation. The result was that colours were sometimes being allocated to the next colour stop.

I spotted this when I noticed that sometimes the minimap graphic (which is actually a tiny Leaflet.js map!) in the control panel area didn't quite match the main map (which is Mapbox GL) - yet they should have been matching:

![Screenshot 2021-03-11 at 22 05 04](https://user-images.githubusercontent.com/361423/110861327-e48bf100-82b5-11eb-94f9-6d94f42ce806.png)

---

I've now rewritten this, in https://github.com/cyclestreets/Mapboxgljs.LayerViewer/commit/3ee321d80bd045f832e12fd53fa5fb26ffa9fb84, to use the 'step' mode, which does what we want properly now.

Here are three examples from some of our favourite friend sites. You can see they now all match the (far easier to understand code) Leaflet.js implementation), and a check of the data against the legend shows things all match up now.

Allerton Bywater:
![Screenshot 2021-03-11 at 22 00 24](https://user-images.githubusercontent.com/361423/110861572-3e8cb680-82b6-11eb-855c-410fc64cd058.png)

Halsnead:
![Screenshot 2021-03-11 at 21 59 57](https://user-images.githubusercontent.com/361423/110861576-3f254d00-82b6-11eb-8413-49e2855e2cf5.png)

Handforth:
![Screenshot 2021-03-11 at 22 03 10](https://user-images.githubusercontent.com/361423/110861560-3af92f80-82b6-11eb-9a49-1725cac32b23.png)

**Comment by Robinlovelace** [comment]
Thanks @mvl22, great description of the issues and fast fix :tada:
